MakeMyDayProject/Controllers/MessageController.cs
using Databases.Neo4j;
using Databases.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MakeMyDayProject.Controllers
{
    public class MessageController : Controller
    {
        RedisFunctions redis = new RedisFunctions();
        Neo4jFunctions neo4j = new Neo4jFunctions();

        // GET: Message
        [Authorize]
        public ActionResult Index(string username)
        {
            try
            {
                if (username == User.Identity.Name)
                    throw new Exception("You can't send message to yourself :D");

                Databases.Neo4j.DomainModel.User userProfile = neo4j.GetUser(username);

                ViewBag.reciever = username;

                var messages = neo4j.GetAllMessagesBetweenUsers(User.Identity.Name, username);

                ViewBag.loggedPicture = neo4j.GetUserProfilePicture(User.Identity.Name).url.Replace('~', ' ');

                redis.RemoveUnreadMessages(User.Identity.Name, username);

                if (userProfile != null)
                    return View(neo4j.GetAllMessagesBetweenUsers(User.Identity.Name, username));
                else
                    throw new Exception("There is no user with that username :(");
            }
            catch (Exception ex)
            {
                return View("CustomError", ex);
            }
        }

        // GET: AllMessages
        [Authorize]
        public ActionResult AllMessages()
        {
            try
            {
                var unreadedMessages = redis.GetAllUnereadedMessagesInfo(User.Identity.Name).ToList();

                unreadedMessages.Reverse();

                return View(unreadedMessages);
            }
            catch (Exception ex)
            {
                return View("CustomError", ex);
            }
        }
    }
}

MakeMyDayProject/Controllers/TopRatedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MakeMyDayProject.Controllers
{
    public class TopRatedController : Controller
    {
        // GET: TopRated
        [Authorize]
        public ActionResult Index()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                return View("CustomError", ex);
            }

        }
    }
}

MakeMyDayProject/Views/Shared/CustomError.cshtml
@model Exception

@{
    ViewBag.Title = "Error";
}

<br />
<h1 class="text-danger">@Model.Message</h1>
<h2 class="text-danger">@Model.InnerException</h2>

MakeMyDayProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Make My Day</title>
    <link href="~/Resource/makemydaytabicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @using Microsoft.AspNet.Identity
    @if (Request.IsAuthenticated)
    {
        <!--NAVBAR FOR LOGGED USER-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-danger fixed-top">

            <!--ICON-->
            <a class="navbar-brand" href="@Url.Action("Index", "Home")" style="margin-left: 60px;">
                <i class="fas fa-grin-squint-tears fa-spin fa-lg"></i>
            </a>

            <!--HAMBURGER FOR RESPONSIVENESS-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!--LINKS NEXT TO ICON THAT WILL BE COLLAPSED WHEN SCREEN IS SMALLER-->
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">
                            <i class="fa fa-home"></i>
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "TopRated")">
                            <i class="fa fa-trophy"></i>
                            Top Rated
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("AllMessages", "Message")">
                            <i class="fa fa-envelope-o"></i>
                            Messages
                            <span class="badge badge-primary badge-pill" id="unreadedMessagesBadge"></span>
                        </a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" id="inputForUserSearch" list="usersForSearch" placeholder="Search users">
                    <datalist id="usersForSearch" name="users" >
                    </datalist>
                    <button class="btn btn-outline-light my-2 my-sm-0" type="button" id="searchButton">Search</button>
                </form>
                @Html.Partial("_LoginPartial")
            </div>
        </nav>
    }
    else
    {
        <!--NAVBAR FOR ANONYM VISITORS-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-danger fixed-top">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")" style="margin-left: 60px;">
                <i class="fas fa-grin-squint-tears fa-spin fa-lg"></i>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">
                            <i class="fa fa-home"></i>
                            Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </nav>
    }

    <!--RENDERING PART-->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Garbage Collectors</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>